In [4]:
import numpy as np

In [5]:
age = [12,23,67]

In [6]:
type(age)

list

In [11]:
import numpy as np

person = [12, 33, 45, 5, 6, 'Neelay', 'Samarth']
personnpa1 = np.array(person)

print(personnpa1)


['12' '33' '45' '5' '6' 'Neelay' 'Samarth']


In [14]:
type(personnpa1)

numpy.ndarray

In [18]:
import numpy as np

arr = np.arange(5, 23, 12)
print(arr)


[ 5 17]


In [19]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.arange(1,10,4)

array([1, 5, 9])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(3)                                                             #random 3 numbers

array([0.63267217, 0.6185274 , 0.52065492])

In [23]:
np.random.randint(1,10,7)                                                      #random 7 numbers between 1 and 10

array([7, 7, 7, 6, 1, 4, 1])

In [32]:
npa=np.arange(24)

In [31]:
npa


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
npa.reshape(2,12)                                                                    #arrange them in 2x12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
npa.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
age = np.array(([34,54,65],[3,5,87],[12,43,32]))
age

array([[34, 54, 65],
       [ 3,  5, 87],
       [12, 43, 32]])

In [36]:
age[1]

array([ 3,  5, 87])

In [37]:
age[1,2]

87

In [39]:
arr1 = np.array([23,45])                                                             #dimension
arr1.ndim

1